### ISSUE TITLE
read_model on windows h5py error

### ISSUE THREAD

**Issue by fabioravila** [decryptr/decryptrModels#1]
Hello,
On Windows When you run the command
`keras_tjmg <- decryptrModels::read_model('tjmg')`

A error occurs:
> Error in keras::load_model_hdf5(file_path) : 
> The h5py Python package is required to save and load models

How do I adjust this on windows to work on R?

**Comment by azeloc** [comment]
It seems like you need to install the h5py package. That's easy to do if you use `pip`:

`pip install --no-binary=h5py h5py`

**Comment by fabioravila** [comment]
Thank you, after trying and searching, I discovered that the problem was because I was using Anconda X86 that does not have a tensorflow package compatible with Windows.

By changing R and Anaconda to x64 I was able to move forward.
