### ISSUE TITLE
Create new model Tutorial

### ISSUE THREAD

**Issue by fabioravila** [decryptr/decryptrModels#2]
Hello,
I would like to ask for a simple, simple tutorial that teaches you to do a training and create a hdf5 template for new captchas, starting from a database of manually classified images.
I want to create new models for different captchas and perform a pull-request

I do not have much experience with R, but I have already been able to make use of almost all the functionalities of its libraries (decriptr and decriptrModels), including prediction, manual classify and download.
I am not able to make a new model in hdf5 without a tutorial, even though it has a base of classified images
Thank you

**Comment by clente** [comment]
See https://decryptr.xyz/docs/custom-model/
